name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
autolabeler:
  - label: "chore"
    title:
      - "/chore/i"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "feature"
    title:
      - "/feat/i"
  - label: "enhancement"
    title:
      - "/refactor/i"
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancments :zap:"
    labels:
      - "enhancement"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":wrench: Maintenance :wrench:"
    labels:
      - "chore"
  - title: ":mortar_board: Code Quality :mortar_board:"
    labels:
      - "code-quality"
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/firstof9/ha-openei/$RESOLVED_VERSION/total.svg)](https://github.com/firstof9/ha-openei/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/firstof9/ha-openei/issues)
