name: Cron actions

on:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - name: Harden Runner
          uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
          with:
            egress-policy: audit

        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false

        - name: HACS validation
          uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # v22.5.0
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: home-assistant/actions/hassfest@ab22029681aa532bfe7de5774a9972d67bfbd2c0 # v1.0.0
