name: Cron actions

on:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - name: Harden Runner
          uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
          with:
            egress-policy: audit

        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          with:
            persist-credentials: false

        - name: HACS validation
          uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # v22.5.0
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: home-assistant/actions/hassfest@e91ad1948e57189485b9c1ad608af0c303946f89 # v1.0.0
