name: Release Drafter

on:
  push:
    branches:
      - master
      - dev
  pull_request_target:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
