name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually enter tag'
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        if: ${{ github.event_name == 'release' }}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_ENV"

      - name: "Set version numbmer"
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/custom_components/openei/const.py
          sed -i '/version/c\  \"version\": \"${{ steps.get_version.outputs.VERSION }}\"' ${{ github.workspace }}/custom_components/openei/manifest.json

      - name: "Set version numbmer"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          sed -i '/VERSION = /c\VERSION = "${{inputs.tags}}"' ${{ github.workspace }}/custom_components/openei/const.py
          sed -i '/version/c\  \"version\": \"${{inputs.tags}}\"' ${{ github.workspace }}/custom_components/openei/manifest.json

      # Pack the openei dir as a zip and upload to the release
      - name: ZIP Dir
        run: |
          cd ${{ github.workspace }}/custom_components/openei
          zip openei.zip -r ./

      - name: 📤 Upload zip to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/openei/openei.zip

      - name: 📤 Upload zip to release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/openei/openei.zip
          tag_name: ${{inputs.tags}}